### ISSUE TITLE
Let engineer lay for a few cells, cancel laying, then order the engineer to move to another cell, the unit does take the shortest path but moves as if still in laying mode.

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MACS-docs#122]
So it still moves only horizontally or vertically.
I think this issue was introduced very recently, I did not notice this before v17.0.4

**Comment by KatekovAnton** [comment]
it still shows a path that unit will go with. fixing this will interfere with that and cause a lot of changes

**Comment by Hruks** [comment]
In the description specified that ANOTHER cell selected for move unit. I think the issue is related with async commands processing for cancel laying and new move path checking before laying actually canceled and path calculated for laying mode.  
As for old path we should simple clear current path when Laying mode cancelled like common Cancel menu item do
