### ISSUE TITLE
Mines and bridges

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MACS-docs#181]
Should be possible to place land mine on top of the bridge.
Land mines should not be triggered when an enemy ship is under the bridge.
Sea mine under the bridge should not be triggered when an enemy land unit is on top of the bridge.

**Comment by KatekovAnton** [comment]
@iindex Hi. I am working on it right now. 

Can you make this change in all unitsets please 
![image](https://github.com/KatekovAnton/MACS-docs/assets/992894/16a660ff-3961-4653-9cd8-1fd3bfdf3162)
otherwise mines will occupy the same z level as bridges and will be constantly engaged in a z-fighting with them.

Thank you.

**Comment by iindex** [comment]
Standard uniset updated: MACs, MACsE, Original, M.A.X. Touch

**Comment by KatekovAnton** [comment]
implemented in v19.1.0
